apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-a
spec:
  selector:
    app: {{ .Release.Name }}-service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
