replicaCount: 1

image:
  repository: 7brandon/app-services-service-react
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}
