apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-b
  labels:
    app: {{ .Release.Name }}-service-b
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service-b
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service-b
    spec:
      containers:
        - name: service-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
