apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-b
spec:
  selector:
    app: {{ .Release.Name }}-service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
