apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-react
  labels:
    app: {{ .Release.Name }}-service-react
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service-react
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service-react
    spec:
      containers:
        - name: service-react
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_SERVICE_A_URL
              value: "http://service-a.default.svc.cluster.local/service-a"
            - name: REACT_APP_SERVICE_B_URL
              value: "http://service-b.default.svc.cluster.local/service-b"
